export const NEED_AUTHORIZATION = "NEED_AUTHORIZATION";
export const LOGIN_WITH_OAUTH_LOADING = "LOGIN_WITH_OAUTH_LOADING";
export const LOGIN_WITH_OAUTH_SUCCESS = "LOGIN_WITH_OAUTH_SUCCESS";
export const LOGIN_WITH_OAUTH_FAIL = "LOGIN_WITH_OAUTH_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const LOGIN_WITH_EMAIL_LOADING = "LOGIN_WITH_EMAIL_LOADING";
export const LOGIN_WITH_EMAIL_SUCCESS = "LOGIN_WITH_EMAIL_SUCCESS";
export const LOGIN_WITH_EMAIL_FAIL = "LOGIN_WITH_EMAIL_FAIL";

export const REGISTER_WITH_EMAIL_LOADING = "REGISTER_WITH_EMAIL_LOADING";
export const REGISTER_WITH_EMAIL_SUCCESS = "REGISTER_WITH_EMAIL_SUCCESS";
export const REGISTER_WITH_EMAIL_FAIL = "REGISTER_WITH_EMAIL_FAIL";

export const ME_LOADING = "ME_LOADING";
export const ME_SUCCESS = "ME_SUCCESS";
export const ME_FAIL = "ME_FAIL";

export const GET_FEATURE = "GET_FEATURE";
export const GET_PROFILE = "GET_PROFILE";

export const GET_MESSAGES_LOADING = "GET_MESSAGES_LOADING";
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";
export const GET_MESSAGES_FAIL = "GET_MESSAGES_FAIL";

export const ADD_MESSAGE_LOADING = "ADD_MESSAGE_LOADING";
export const ADD_MESSAGE_SUCCESS = "ADD_MESSAGE_SUCCESS";
export const ADD_MESSAGE_FAIL = "ADD_MESSAGE_FAIL";

export const DELETE_MESSAGE_LOADING = "DELETE_MESSAGE_LOADING";
export const DELETE_MESSAGE_SUCCESS = "DELETE_MESSAGE_SUCCESS";
export const DELETE_MESSAGE_FAIL = "DELETE_MESSAGE_FAIL";

export const EDIT_MESSAGE_LOADING = "EDIT_MESSAGE_LOADING";
export const EDIT_MESSAGE_SUCCESS = "EDIT_MESSAGE_SUCCESS";
export const EDIT_MESSAGE_FAIL = "EDIT_MESSAGE_FAIL";
export const CLEAR_MESSAGE_ERROR = "CLEAR_MESSAGE_ERROR";

export const GET_USERS_LOADING = "GET_USERS_LOADING";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";

export const GET_PROFILE_LOADING = "GET_PROFILE_LOADING";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";

export const EDIT_USER_LOADING = "EDIT_USER_LOADING";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAIL = "EDIT_USER_FAIL";

export const DELETE_USER_LOADING = "DELETE_USER_LOADING";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

export const RESEED_DATABASE_LOADING = "RESEED_DATABASE_LOADING";
export const RESEED_DATABASE_SUCCESS = "RESEED_DATABASE_SUCCESS";
export const RESEED_DATABASE_FAIL = "RESEED_DATABASE_FAIL";

export const LOAD_ARTICLES = "LOAD_ARTICLES";
export const RESET_ARTICLES = "RESET_ARTICLES";
export const LOAD_MORE_ARTICLES = "LOAD_MORE_ARTICLES";
export const LOAD_MY_ARTICLES = "LOAD_MY_ARTICLES";
export const LOAD_ARTICLES_POPULAR = "LOAD_ARTICLES_POPULAR";
export const LOAD_ARTICLE_DETAILS_SUCCESS = "LOAD_ARTICLE_DETAILS_SUCCESS";
export const DELETE_ARTICLE_SUCCESS = "DELETE_ARTICLE_SUCCESS";

export const RESET_PUBLISH_STATUS = "RESET_PUBLISH_STATUS";
export const EDIT_ARTICLE = "EDIT_ARTICLE";
export const ADD_NEW_ARTICLE_LOADING = "ADD_NEW_ARTICLE_LOADING";
export const ADD_NEW_ARTICLE_SUCCESS = "ADD_NEW_ARTICLE_SUCCESS";
export const ADD_NEW_ARTICLE_FAIL = "ADD_NEW_ARTICLE_FAIL";

export const UPLOAD_FEATURE_IMAGE_SUCCESS = "UPLOAD_FEATURE_IMAGE_SUCCESS";
export const UPLOAD_FEATURE_IMAGE_LOADING = "UPLOAD_FEATURE_IMAGE_LOADING";
export const CANNOT_PUBLISH_WHILE_UPLOADING_IMAGE = "CANNOT_PUBLISH_WHILE_UPLOADING_IMAGE";

export const ADD_COMMENT = "ADD_COMMENT";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const COMPOSING_COMMENT = "COMPOSING_COMMENT";
export const LOAD_COMMENTS = "LOAD_COMMENTS";
export const LOAD_COMMENTS_SUCCESS = "LOAD_COMMENTS_SUCCESS";
